"""Strict Smart-Money + Price-Action decision engine: **BUY / SELL / WAIT**.

This module is deliberately stricter than :mod:`marketobserver.smc`. It is a
*hard* gate chain evaluated in the order below; it stops at the first failure, so
the output is a single decision plus the exact reason it was refused. Nothing
here is generated by a language model: every number is derived from closed
candles supplied by the caller.

Gate order (each step may end the analysis):

1. **Trend (4H)** — structure must be HH + HL (longs only) or LH + LL (shorts
   only). Anything else is ``WAIT``.
2. **Liquidity map** — equal highs/lows, wick-only sweeps, premium/discount
   positioning and the next resting-liquidity target.
3. **Volume filter (overrides everything)** — ``RVOL < 1.0`` is a weak market
   and means ``WAIT``; a break printed on weak volume is an *invalid break*;
   OBV or a counter-direction volume spike rejects the trade outright.
4. **Structure confirmation** — a BOS or CHoCH that *closed* with the trend on
   15m or 1H, not superseded by an opposing break. Wick-only breaks are sweeps,
   never confirmations; a break on weak volume is a fake break and is ignored.
5. **Candle confirmation** — engulfing / pin bar / star / inside bar aligned
   with the trend; an opposing print on the trigger means ``WAIT``.
6. **Entry zone** — an order block or fair-value gap that price *returns* to
   after the confirmation, and never chased.
7. **Risk management** — stop beyond structure, target at the next liquidity
   level, reward:risk >= 2.0 or ``WAIT``.

Only when every gate passes is the output ``BUY`` (long) or ``SELL`` (short).

RSI, SMA20, SMA50 and ATR are computed on every timeframe and reported as
context. They are deliberately *not* gates: the decision is structural, and a
moving-average cross on its own is exactly the kind of signal this engine is
meant to refuse.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from statistics import mean

from .analysis import rsi_wilder
from .market_data import Candle
from .smc import (
    Level,
    TimeframeSMC,
    Zone,
    analyze_timeframe,
    drop_forming,
    liquidity_pools,
    stamp,
)

# --------------------------------------------------------------------------- #
# thresholds — every one of them is explicit so a report can be audited
# --------------------------------------------------------------------------- #
RVOL_MIN = 1.0            # step 3: below this the market is "weak" -> WAIT
BREAK_VOLUME_MIN = 1.10   # step 3/4: a break under this multiple is a fake break
MIN_RISK_REWARD = 2.0     # step 7: reward:risk floor on the first target
CONTRA_SPIKE_RATIO = 2.2  # a spike this size against the trade rejects it
CONFIRM_MAX_AGE = 8       # bars: how long a confirmation stays tradeable
ZONE_MAX_AGE = 40         # bars: an order block / gap older than this is stale
ZONE_TOLERANCE_ATR = 1.5  # "price is at the zone" = within 1.5 ATR ...
ZONE_TOLERANCE_PCT = 0.003  # ... or 0.3% of price, whichever is wider

BULLISH_PRINTS = {"engulfing_bullish", "hammer", "inverted_hammer", "morning_star", "piercing_line", "dragonfly_doji"}
BEARISH_PRINTS = {"engulfing_bearish", "shooting_star", "evening_star", "dark_cloud_cover", "gravestone_doji"}
NEUTRAL_PRINTS = {"doji", "inside_bar", "outside_bar"}

ENTRY_TIMEFRAME = "15m"
NO_STAMP = datetime(1, 1, 1, tzinfo=timezone.utc)  # "no confirmation time" sentinel
SETUP_TIMEFRAME = "1h"
TREND_TIMEFRAME = "4h"
TIMEFRAMES = (TREND_TIMEFRAME, SETUP_TIMEFRAME, ENTRY_TIMEFRAME)


# --------------------------------------------------------------------------- #
# data structures
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Step:
    """One gate of the chain, with the numbers that decided it.

    ``reached`` is False for the gates behind the first failure: the chain stops
    there, so those gates were never a reason for the verdict.
    """

    number: int
    key: str
    title: str
    passed: bool
    detail: str
    numbers: dict = field(default_factory=dict)
    reached: bool = True

    @property
    def state(self) -> str:
        return "pass" if self.passed else ("fail" if self.reached else "stopped")


@dataclass(frozen=True)
class LiquidityTarget:
    kind: str
    price: float
    distance_pct: float
    direction: str  # up | down


@dataclass(frozen=True)
class IndicatorRead:
    """RSI / SMA20 / SMA50 / ATR per timeframe.

    Reported as context only. The gate chain is structure, liquidity, volume,
    candles, zone and reward:risk — a moving-average cross is never allowed to
    open a trade on its own, so these numbers explain the backdrop, they do not
    vote.
    """

    timeframe: str
    rsi: float
    sma20: float
    sma50: float
    atr: float
    alignment: str  # bullish | bearish | flat
    note: str


@dataclass(frozen=True)
class StrictDecision:
    asset_key: str
    asset_name_en: str
    asset_name_ar: str
    quote: str
    decimals: int
    price: float
    source: str
    as_of: str
    timeframe_of_price: str

    trend: str  # bullish | bearish | none
    trend_detail: str

    liquidity_target: str  # up | down | both
    liquidity_detail: str
    liquidity_above: LiquidityTarget | None
    liquidity_below: LiquidityTarget | None
    premium_discount: str
    position_pct: float
    equal_highs: tuple[float, ...]
    equal_lows: tuple[float, ...]
    sweeps: tuple[str, ...]

    rvol: float
    rvol_timeframe: str
    rvol_setup: float
    volume_status: str  # strong | weak
    volume_detail: str
    obv_slope: float
    buy_pct: float | None

    structure_confirmed: bool
    structure_detail: str
    structure_event: str  # BOS | CHoCH | none
    structure_timeframe: str
    structure_time: str
    structure_level: float

    candle_signal: str
    candle_direction: str
    candle_timeframe: str
    candle_time: str
    candle_detail: str

    entry_low: float
    entry_high: float
    entry_kind: str
    entry_detail: str

    stop: float
    stop_timeframe: str
    stop_detail: str

    take_profit: float
    take_profit_two: float
    target_detail: str

    risk: float
    reward: float
    risk_reward: float

    indicators: tuple[IndicatorRead, ...]
    steps: tuple[Step, ...]
    decision: str  # buy | sell | wait
    side: str  # long | short | none
    confidence: str  # high | medium | low
    reasons: tuple[str, ...]
    flags: tuple[str, ...] = ()
    views: tuple[TimeframeSMC, ...] = ()

    @property
    def failed_steps(self) -> tuple[Step, ...]:
        """The gate that stopped the chain (empty when the trade is confirmed)."""
        return tuple(step for step in self.steps if step.reached and not step.passed)

    @property
    def passed_steps(self) -> tuple[Step, ...]:
        return tuple(step for step in self.steps if step.passed)

    @property
    def stopped_at(self) -> int:
        failed = self.failed_steps
        return failed[0].number if failed else 0

    @property
    def decision_label(self) -> str:
        return {"buy": "BUY", "sell": "SELL", "wait": "WAIT"}[self.decision]


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def parse_stamp(text: str) -> datetime:
    """``2026-09-16 08:00 UTC`` -> aware datetime (UTC)."""
    value = (text or "").replace("UTC", "").strip()
    try:
        parsed = datetime.strptime(value, "%Y-%m-%d %H:%M")
    except ValueError:
        return NO_STAMP
    return parsed.replace(tzinfo=timezone.utc)


def recent_obv_slope(candles: list[Candle], window: int = 20) -> float:
    """Signed share of the volume traded in the last ``window`` candles.

    The wider ``volume_stats.obv_slope`` compares two halves of a cumulative
    series, so a market that fell for a day and then reclaimed a level can still
    read negative — which would reject exactly the pullback entries this engine
    hunts. This local reading answers the question the filter actually cares
    about: over the recent window, did up-volume or down-volume dominate? A
    negative number for a long (or positive for a short) is a contradiction.
    """
    tail = list(candles)[-(window + 1):]
    if len(tail) < 3:
        return 0.0
    obv = 0.0
    total = 0.0
    for index in range(1, len(tail)):
        change = tail[index].close - tail[index - 1].close
        direction = 1.0 if change > 0 else -1.0 if change < 0 else 0.0
        obv += direction * tail[index].volume
        total += tail[index].volume
    return round(obv / total * 100, 3) if total else 0.0


# --------------------------------------------------------------------------- #
# step 1 — 4H trend
# --------------------------------------------------------------------------- #
def trend_from_swings(swings: tuple | list) -> tuple[str, str, dict]:
    """HH + HL => bullish, LH + LL => bearish, anything else => none.

    Only *labelled* fractal pivots count, and the most recent labelled high and
    low must agree. A ladder that mixes (e.g. HH + LL, or EQH + HL) is not a
    trend, and a non-trend is not tradeable.
    """
    highs = [swing for swing in swings if swing.is_high and swing.label]
    lows = [swing for swing in swings if not swing.is_high and swing.label]
    if not highs or not lows:
        return "none", "not enough confirmed and labelled pivots to define a structure", {}
    high, low = highs[-1], lows[-1]
    detail = (f"last swing high {high.price:g} ({high.label}) at {high.time}, "
              f"last swing low {low.price:g} ({low.label}) at {low.time}")
    numbers = {
        "high": round(high.price, 8), "high_label": high.label, "high_time": high.time,
        "low": round(low.price, 8), "low_label": low.label, "low_time": low.time,
        "highs": [(item.label, round(item.price, 8)) for item in highs[-3:]],
        "lows": [(item.label, round(item.price, 8)) for item in lows[-3:]],
    }
    if high.label == "HH" and low.label == "HL":
        return "bullish", detail + " | HH + HL ladder -> longs only", numbers
    if high.label == "LH" and low.label == "LL":
        return "bearish", detail + " | LH + LL ladder -> shorts only", numbers
    return "none", detail + f" | {high.label} + {low.label} is not a HH+HL or LH+LL ladder", numbers


# --------------------------------------------------------------------------- #
# step 2 — liquidity map
# --------------------------------------------------------------------------- #
def _target(level: Level, price: float, direction: str) -> LiquidityTarget:
    distance = abs(level.price - price) / price * 100 if price else 0.0
    return LiquidityTarget(level.kind, round(level.price, 8), round(distance, 2), direction)


def liquidity_map(views: dict[str, TimeframeSMC], side: str, price: float) -> dict:
    """Equal highs/lows, sweeps and the resting liquidity price should run into
    next. Both sides are always reported; only the trade side becomes a target.
    """
    highest = views.get(TREND_TIMEFRAME)
    pools: list[tuple[str, Level]] = []
    for timeframe in TIMEFRAMES:
        view = views.get(timeframe)
        if view is None:
            continue
        pools.extend((timeframe, level) for level in liquidity_pools(view))
    above = sorted((item for item in pools if item[1].price > price), key=lambda item: item[1].price)
    below = sorted((item for item in pools if item[1].price < price), key=lambda item: -item[1].price)
    liquidity_above = _target(above[0][1], price, "up") if above else None
    liquidity_below = _target(below[0][1], price, "down") if below else None
    if side == "long":
        target, direction = liquidity_above, "up"
    elif side == "short":
        target, direction = liquidity_below, "down"
    else:
        target, direction = None, "both"
    sweeps: list[str] = []
    for timeframe in TIMEFRAMES:
        view = views.get(timeframe)
        if view is None:
            continue
        for event in view.events:
            if event.kind == "sweep":
                sweeps.append(f"{timeframe} swept {event.level:g} ({event.direction}) at {event.time}")
    equal_highs = tuple(sorted({round(level.price, 8) for _, level in pools if level.kind == "equal_highs"}))
    equal_lows = tuple(sorted({round(level.price, 8) for _, level in pools if level.kind == "equal_lows"}))
    if highest is None:  # pragma: no cover - decide() refuses to run without 4H
        return {"target": target, "direction": direction, "above": liquidity_above, "below": liquidity_below,
                "equal_highs": equal_highs, "equal_lows": equal_lows, "sweeps": tuple(sweeps[-4:]),
                "position_pct": 50.0, "zone": "equilibrium", "detail": "no 4H view available"}
    range_high, range_low = highest.range_high, highest.range_low
    position = (price - range_low) / (range_high - range_low) if range_high > range_low else 0.5
    zone = "premium" if position >= 0.6 else "discount" if position <= 0.4 else "equilibrium"
    parts = [f"price sits at {position * 100:.1f}% of the 4H range {range_low:g}-{range_high:g} ({zone})"]
    parts.append(f"nearest pool above {liquidity_above.price:g} ({liquidity_above.kind}, {liquidity_above.distance_pct}% away)"
                 if liquidity_above else "no pool above the price")
    parts.append(f"nearest pool below {liquidity_below.price:g} ({liquidity_below.kind}, {liquidity_below.distance_pct}% away)"
                 if liquidity_below else "no pool below the price")
    if equal_highs:
        parts.append(f"equal highs {', '.join(f'{value:g}' for value in equal_highs[:3])} (sell-side liquidity resting above)")
    if equal_lows:
        parts.append(f"equal lows {', '.join(f'{value:g}' for value in equal_lows[:3])} (buy-side liquidity resting below)")
    if sweeps:
        parts.append(f"last wick sweep: {sweeps[-1]}")
    return {"target": target, "direction": direction, "above": liquidity_above, "below": liquidity_below,
            "equal_highs": equal_highs, "equal_lows": equal_lows, "sweeps": tuple(sweeps[-4:]),
            "position_pct": round(position * 100, 1), "zone": zone, "detail": "; ".join(parts)}


# --------------------------------------------------------------------------- #
# step 4 helper — BOS / CHoCH with a volume check (also used by step 3)
# --------------------------------------------------------------------------- #
def break_analysis(view: TimeframeSMC | None, side: str) -> dict:
    """Aligned / opposed / fake breaks on one timeframe.

    A break only counts when a candle *closed* through the swing (the detector
    already refuses wick-only breaks) and the break candle traded at least
    ``BREAK_VOLUME_MIN`` times its average volume. A break below that is a fake
    break: it is dropped here and never confirms anything.
    """
    if view is None or side not in {"long", "short"}:
        return {"ok": False, "detail": "no confirmation timeframe", "event": None, "ignored": [],
                "aligned": [], "opposed": [], "sweeps": [], "available": False}
    wanted = "bullish" if side == "long" else "bearish"
    last_index = view.candles - 1
    breaks = [event for event in view.events if event.kind in {"bos", "choch"}]
    aligned = [event for event in breaks if event.direction == wanted]
    opposed = [event for event in breaks if event.direction != wanted]
    recent_aligned = [event for event in aligned if last_index - event.index <= CONFIRM_MAX_AGE]
    valid = [event for event in recent_aligned if event.volume_ratio >= BREAK_VOLUME_MIN]
    ignored = [event for event in recent_aligned if event.volume_ratio < BREAK_VOLUME_MIN]
    sweeps = [event for event in view.events if event.kind == "sweep" and event.direction == wanted]
    event = valid[-1] if valid else None
    stale_by = opposed[-1] if opposed and (event is None or opposed[-1].index > event.index) else None
    if not recent_aligned:
        detail = f"{view.timeframe}: no aligned BOS/CHoCH closed in the last {CONFIRM_MAX_AGE} candles"
    elif not valid:
        detail = (f"{view.timeframe}: every aligned break was a fake break ("
                  + ", ".join(f"{item.label} {item.time} on {item.volume_ratio}x" for item in ignored)
                  + f") below the {BREAK_VOLUME_MIN}x volume requirement")
    else:
        detail = (f"{view.timeframe}: {event.label} {event.direction} at {event.time} closed through "
                  f"{event.level:g} on {event.volume_ratio}x volume")
    if event is not None and stale_by is not None:
        detail = (f"{view.timeframe}: aligned {event.label} {event.direction} at {event.time} was superseded "
                  f"by an opposing {stale_by.label} at {stale_by.time}")
        event = None
    return {"ok": event is not None, "detail": detail, "event": event, "ignored": ignored,
            "aligned": aligned, "opposed": opposed, "sweeps": sweeps, "available": bool(recent_aligned)}


def confirmation_analysis(views: dict[str, TimeframeSMC], side: str) -> dict:
    """Prefer the entry timeframe (15m), fall back to the setup timeframe (1H)."""
    results: dict[str, dict] = {}
    for timeframe in (ENTRY_TIMEFRAME, SETUP_TIMEFRAME):
        view = views.get(timeframe)
        if view is not None:
            results[timeframe] = break_analysis(view, side)
    for timeframe in (ENTRY_TIMEFRAME, SETUP_TIMEFRAME):
        if results.get(timeframe, {}).get("ok"):
            return {"timeframe": timeframe, **results[timeframe], "all": results}
    if not results:
        return {"ok": False, "timeframe": "", "detail": "no 15m or 1H candles were supplied", "event": None,
                "ignored": [], "aligned": [], "opposed": [], "sweeps": [], "available": False, "all": {}}
    fallback = next(iter(results))
    return {"timeframe": fallback, **results[fallback], "all": results}


# --------------------------------------------------------------------------- #
# step 3 — volume filter
# --------------------------------------------------------------------------- #
def volume_filter(views: dict[str, TimeframeSMC], candles: dict[str, list[Candle]], side: str,
                  confirmation: dict) -> dict:
    """RVOL, spike contradiction, OBV slope and break-candle validation.

    This gate overrides the rest of the chain: if volume contradicts the
    direction, the trade is rejected no matter how clean the structure is.
    """
    trigger = views.get(ENTRY_TIMEFRAME) or views.get(SETUP_TIMEFRAME)
    if trigger is None:  # pragma: no cover - decide() always has at least 4H, not 15m/1h
        return {"passed": False, "rvol": 0.0, "timeframe": "", "status": "weak", "setup_rvol": 0.0,
                "detail": "no entry or setup timeframe was supplied", "problems": (), "obv_slope": 0.0, "buy_pct": None}
    rvol = trigger.volume.relative
    setup_view = views.get(SETUP_TIMEFRAME)
    setup_rvol = setup_view.volume.relative if setup_view else rvol
    series = candles.get(trigger.timeframe) or []
    obv = recent_obv_slope(series)
    obv_full = trigger.volume.obv_slope
    buy_pct = trigger.volume.buy_pct
    status = "strong" if min(rvol, setup_rvol) >= RVOL_MIN else "weak"
    problems: list[str] = []
    if rvol < RVOL_MIN:
        problems.append(f"weak market: RVOL {rvol:.2f}x is below the {RVOL_MIN:.2f}x floor on {trigger.timeframe}")
    if setup_view is not None and setup_view is not trigger and setup_rvol < RVOL_MIN:
        problems.append(f"weak market: RVOL {setup_rvol:.2f}x is below the {RVOL_MIN:.2f}x floor on "
                        f"{setup_view.timeframe}, the timeframe the setup has to be confirmed on")
    if confirmation.get("ignored"):
        weakest = min(event.volume_ratio for event in confirmation["ignored"])
        problems.append(f"invalid break: the {confirmation['timeframe']} break candle printed {weakest:.2f}x "
                        f"against the {BREAK_VOLUME_MIN:.2f}x requirement")
    wanted_sign = 1 if side == "long" else -1
    if obv and obv * wanted_sign < 0:
        problems.append(f"OBV contradicts the {'long' if side == 'long' else 'short'}: net flow over the last "
                        f"{len(series[-21:])} {trigger.timeframe} candles is {obv:+.2f}% of traded volume")
    spikes = trigger.volume.spikes
    if spikes:
        index, when, ratio = spikes[-1]
        series = candles.get(trigger.timeframe) or []
        # a spike on the newest closed bar that closed against the trade is a
        # direct contradiction of the direction the trade needs
        if index == trigger.candles - 1 and index < len(series):
            candle = series[index]
            against = candle.close < candle.open if side == "long" else candle.close > candle.open
            if ratio >= CONTRA_SPIKE_RATIO and against:
                problems.append(f"{side} rejected: {when} volume spike {ratio}x closed "
                                f"{'down' if side == 'long' else 'up'} against the trade")
    words = [f"{trigger.timeframe} RVOL {rvol:.2f}x"]
    if setup_view is not None and setup_view is not trigger:
        words.append(f"{setup_view.timeframe} RVOL {setup_rvol:.2f}x")
    if buy_pct is not None:
        words.append(f"taker buys {buy_pct}%")
    words.append(f"volume {trigger.volume.trend} ({trigger.volume.trend_change_pct:+.0f}%)")
    words.append(f"OBV net flow {obv:+.2f}% of the last {min(len(series), 21)} candles "
                 f"(full-window OBV slope {obv_full:+.3f})")
    if spikes:
        words.append(f"last spike {spikes[-1][2]}x at {spikes[-1][1]}")
    if confirmation.get("event") is not None:
        words.append(f"break candle {confirmation['event'].volume_ratio}x")
    detail = "; ".join(words)
    if problems:
        detail = "volume filter failed -> trade rejected | " + " · ".join(problems) + " | " + detail
    return {"passed": not problems, "rvol": rvol, "timeframe": trigger.timeframe, "status": status,
            "setup_rvol": setup_rvol, "detail": detail, "problems": tuple(problems), "obv_slope": obv,
            "buy_pct": buy_pct}


# --------------------------------------------------------------------------- #
# step 5 — candle confirmation
# --------------------------------------------------------------------------- #
def candle_confirmation(view: TimeframeSMC | None, side: str) -> dict:
    if view is None:
        return {"passed": False, "signal": "none", "direction": "none", "time": "",
                "detail": "no confirmation timeframe", "aligned": ()}
    wanted = BULLISH_PRINTS if side == "long" else BEARISH_PRINTS
    opposed = BEARISH_PRINTS if side == "long" else BULLISH_PRINTS
    last_index = view.candles - 1
    window = [print_ for print_ in view.patterns if last_index - print_.index <= CONFIRM_MAX_AGE]
    aligned = [print_ for print_ in window if print_.name in wanted]
    against = [print_ for print_ in window if print_.name in opposed]
    neutral = [print_ for print_ in window if print_.name in NEUTRAL_PRINTS]
    newest = None
    for print_ in sorted(window, key=lambda item: item.index):
        if print_.name in wanted or print_.name in opposed:
            newest = print_
    if newest is not None and newest.name in opposed:
        return {"passed": False, "signal": newest.name, "direction": newest.direction, "time": newest.time,
                "detail": f"opposite signal on {view.timeframe}: {newest.name} at {newest.time} ({newest.context}) "
                          f"rejects the {'long' if side == 'long' else 'short'}",
                "aligned": tuple(print_.name for print_ in aligned)}
    if not aligned:
        extra = (f" (only neutral prints: {', '.join(dict.fromkeys(print_.name for print_ in neutral))})"
                 if neutral else "")
        return {"passed": False, "signal": neutral[-1].name if neutral else "none",
                "direction": "neutral" if neutral else "none", "time": neutral[-1].time if neutral else "",
                "detail": f"no {view.timeframe} candle print aligned with the trade in the last "
                          f"{CONFIRM_MAX_AGE} candles{extra}", "aligned": ()}
    print_ = aligned[-1]
    return {"passed": True, "signal": print_.name, "direction": print_.direction, "time": print_.time,
            "detail": f"{view.timeframe} {print_.name} at {print_.time} ({print_.context}) agrees with the trade",
            "aligned": tuple(item.name for item in aligned)}


# --------------------------------------------------------------------------- #
# step 6 — entry zone (order block / fair value gap) + return to the zone
# --------------------------------------------------------------------------- #
def zone_candidates(view: TimeframeSMC, side: str, decimals: int) -> list[Zone]:
    """Every order block and fair-value gap on the trade side, best first.

    Same preference order as :func:`marketobserver.smc.best_zone` — fresh order
    block, order block, fresh gap, gap — but the strict engine has to inspect the
    whole list, because the zone that can be traded is the one price actually
    returned to, not necessarily the first one in the ranking.
    """
    bullish = side == "long"
    wanted = "bullish" if bullish else "bearish"
    options: list[tuple[int, int, Zone]] = []
    for block in view.blocks:
        if block.kind != wanted:
            continue
        rank = (0 if block.fresh else 2) - (1 if block.swept_liquidity else 0)
        detail = (f"order block {block.bottom:.{decimals}f}-{block.top:.{decimals}f} @ {block.time} | "
                  f"displacement {block.displacement} ATR | volume {block.volume_ratio}x | "
                  f"{'fresh' if block.fresh else 'mitigated'}"
                  + (" | formed after a liquidity sweep" if block.swept_liquidity else "")
                  + f" | after {block.caused_by.upper()}")
        options.append((rank, block.index, Zone("order_block", round(block.bottom, decimals),
                                                round(block.top, decimals), block.index, block.time, block.fresh, detail)))
    for gap in view.gaps:
        if gap.kind != wanted or gap.mitigated:
            continue
        fresh = gap.filled_pct < 25
        detail = (f"fair value gap {gap.bottom:.{decimals}f}-{gap.top:.{decimals}f} @ {gap.time} | "
                  f"filled {gap.filled_pct}% | displacement {gap.displacement}")
        options.append((1 if fresh else 3, gap.index,
                        Zone("fair_value_gap", round(gap.bottom, decimals), round(gap.top, decimals), gap.index,
                             gap.time, fresh, detail)))
    options.sort(key=lambda item: (item[0], -item[1]))
    return [item[2] for item in options]


def _zone_candidate(view: TimeframeSMC, candles: dict[str, list[Candle]], side: str, price: float,
                    decimals: int, confirm_time: str) -> dict:
    """All zones of one timeframe, judged in preference order."""
    tolerance = max(view.atr * ZONE_TOLERANCE_ATR, price * ZONE_TOLERANCE_PCT)
    side_word = "long" if side == "long" else "short"
    candidates = zone_candidates(view, side, decimals)
    if not candidates:
        return {"ok": False, "zone": None, "tolerance": tolerance,
                "detail": f"no {view.timeframe} order block or fair-value gap on the {side_word} side"}
    confirmed_at = parse_stamp(confirm_time)
    has_confirmation = confirmed_at != NO_STAMP
    series = candles.get(view.timeframe) or []
    rejections: list[str] = []
    first: dict | None = None
    for zone in candidates:
        base = (f"{view.timeframe} {zone.kind} {zone.bottom:g}-{zone.top:g} @ {zone.time} "
                f"({'fresh' if zone.fresh else 'mitigated'})")
        age = view.candles - 1 - zone.index
        if age > ZONE_MAX_AGE:
            rejections.append(f"{base}: {age} candles old (limit {ZONE_MAX_AGE})")
            continue
        if has_confirmation and parse_stamp(zone.time) > confirmed_at:
            rejections.append(f"{base}: created after the confirmation")
            continue
        touched: list[str] = []
        for candle in series:
            when = candle.timestamp if candle.timestamp.tzinfo else candle.timestamp.replace(tzinfo=timezone.utc)
            if has_confirmation and when <= confirmed_at:
                continue
            # a real return to the zone means the candle's range overlaps it,
            # not merely that it traded somewhere on the same side of it
            if candle.low <= zone.top and candle.high >= zone.bottom:
                touched.append(stamp(candle))
        anchor = zone.top if side == "long" else zone.bottom
        distance = abs(price - anchor)
        result = {"ok": False, "zone": zone, "tolerance": tolerance, "distance": round(distance, decimals),
                  "touched": tuple(touched[-3:])}
        if not touched:
            result["detail"] = f"price has not returned to the {base} since the confirmation at {confirm_time}"
        elif distance > tolerance:
            result["detail"] = (f"price returned to the {base} ({touched[-1]}) but is now {round(distance, decimals)} "
                                f"away (tolerance {round(tolerance, decimals)}): entering here is chasing")
        else:
            result.update({"ok": True,
                           "detail": f"price returned into the {base} at {touched[-1]} and is inside it now "
                                     f"({round(distance, decimals)} from the entry edge, tolerance "
                                     f"{round(tolerance, decimals)})"})
            return result
        first = first or result
    if first is None:  # every candidate was stale / pre-dated
        return {"ok": False, "zone": candidates[0], "tolerance": tolerance,
                "detail": f"{view.timeframe}: no order block or gap is both recent enough and older than the "
                          f"confirmation" + (f" ({'; '.join(rejections[:2])})" if rejections else "")}
    if rejections:
        first = dict(first)
        first["detail"] = first["detail"] + " | also skipped: " + "; ".join(rejections[:2])
    return first


def entry_zone(views: dict[str, TimeframeSMC], candles: dict[str, list[Candle]], side: str, price: float,
               decimals: int, confirm_time: str, confirm_timeframe: str) -> dict:
    """The zone must be an order block or a fair-value gap that existed before
    the confirmation, price must have traded back into it *after* the
    confirmation, and it must still be within tolerance now. Otherwise: WAIT.

    The zone is read from the leg that produced the confirmation first (15m),
    then the setup timeframe (1H), then the trend timeframe (4H) — the origin of
    a break is always on the timeframe the break printed on.
    """
    if side not in {"long", "short"}:
        return {"ok": False, "zone": None, "tolerance": 0.0, "detail": "no trade side to look for a zone on"}
    order = [timeframe for timeframe in (confirm_timeframe, SETUP_TIMEFRAME, TREND_TIMEFRAME)
             if timeframe in views]
    if not order:
        return {"ok": False, "zone": None, "tolerance": 0.0,
                "detail": "no timeframe to read an order block or fair-value gap from"}
    failures: list[dict] = []
    for timeframe in order:
        result = _zone_candidate(views[timeframe], candles, side, price, decimals, confirm_time)
        if result["ok"]:
            return result
        failures.append(result)
    first = failures[0]
    if len(failures) > 1:
        first = dict(first)
        first["detail"] = first["detail"] + " | " + " | ".join(item["detail"] for item in failures[1:])
    return first


# --------------------------------------------------------------------------- #
# step 7 — risk management
# --------------------------------------------------------------------------- #
def risk_plan(views: dict[str, TimeframeSMC], side: str, zone: Zone, price: float, decimals: int,
              min_risk_reward: float = MIN_RISK_REWARD) -> dict:
    highest = views.get(TREND_TIMEFRAME) or views.get(SETUP_TIMEFRAME)
    setup = views.get(SETUP_TIMEFRAME) or highest
    if highest is None or zone is None:  # pragma: no cover - pushed by decide() only
        return {"ok": False, "detail": "no zone to build a plan from"}
    buffer_ = max(highest.atr * 0.2, price * 0.0012)
    pivots = (setup or highest).swings
    candidates: list[tuple[float, str, str]] = []
    if side == "long":
        entry = zone.top
        guards = [swing.price for swing in pivots if not swing.is_high and swing.price < entry]
        structure_low = min([swing.price for swing in pivots if not swing.is_high] or [highest.range_low])
        anchor = max(guards) if guards else min(structure_low, zone.bottom)
        stop = round(anchor - buffer_, decimals)
        stop_detail = (f"{entry:g} entry, stop {stop:g} below the swing low {anchor:g} on "
                       f"{(setup or highest).timeframe} plus a {round(buffer_, decimals)} buffer")
        risk = entry - stop
        for timeframe, view in views.items():
            candidates.extend((level.price, level.kind, timeframe) for level in liquidity_pools(view)
                              if level.price > entry)
        source = "liquidity pool"
        if not candidates:
            candidates.extend((level.price, level.kind, highest.timeframe) for level in highest.levels
                              if level.price > entry and level.kind != "equal_lows")
            source = "4H level"
        if not candidates and highest.range_high > entry:
            candidates.append((highest.range_high, "4h range high", highest.timeframe))
            source = "range extreme"
        if not candidates:
            return {"ok": False, "entry": round(entry, decimals), "stop": stop, "risk": round(risk, decimals),
                    "ratio": 0.0, "stop_detail": stop_detail,
                    "detail": "no liquidity sits above the entry, so there is no honest first target"}
        target_one, target_kind, target_timeframe = min(candidates, key=lambda item: item[0])
        reward = target_one - entry
        ratio = round(reward / risk, 2) if risk > 0 and reward > 0 else 0.0
        beyond = [value for value, _, _ in candidates if value > target_one]
        target_two = round(min(beyond), decimals) if beyond else 0.0
    else:
        entry = zone.bottom
        guards = [swing.price for swing in pivots if swing.is_high and swing.price > entry]
        structure_high = max([swing.price for swing in pivots if swing.is_high] or [highest.range_high])
        anchor = min(guards) if guards else max(structure_high, zone.top)
        stop = round(anchor + buffer_, decimals)
        stop_detail = (f"{entry:g} entry, stop {stop:g} above the swing high {anchor:g} on "
                       f"{(setup or highest).timeframe} plus a {round(buffer_, decimals)} buffer")
        risk = stop - entry
        for timeframe, view in views.items():
            candidates.extend((level.price, level.kind, timeframe) for level in liquidity_pools(view)
                              if level.price < entry)
        source = "liquidity pool"
        if not candidates:
            candidates.extend((level.price, level.kind, highest.timeframe) for level in highest.levels
                              if level.price < entry and level.kind != "equal_highs")
            source = "4H level"
        if not candidates and highest.range_low < entry:
            candidates.append((highest.range_low, "4h range low", highest.timeframe))
            source = "range extreme"
        if not candidates:
            return {"ok": False, "entry": round(entry, decimals), "stop": stop, "risk": round(risk, decimals),
                    "ratio": 0.0, "stop_detail": stop_detail,
                    "detail": "no liquidity sits below the entry, so there is no honest first target"}
        target_one, target_kind, target_timeframe = max(candidates, key=lambda item: item[0])
        reward = entry - target_one
        ratio = round(reward / risk, 2) if risk > 0 and reward > 0 else 0.0
        beyond = [value for value, _, _ in candidates if value < target_one]
        target_two = round(max(beyond), decimals) if beyond else 0.0
    ok = ratio >= min_risk_reward
    detail = (f"reward:risk {ratio}:1 to the first target (minimum {min_risk_reward}:1) | {stop_detail} | "
              f"target {target_one:g} = {target_kind} on {target_timeframe} ({source}) for a reward of "
              f"{round(reward, decimals)} against a risk of {round(risk, decimals)}")
    if not ok:
        detail += (" | rejected: the first liquidity level does not pay for the stop, so there is no trade"
                   if reward > 0 else " | rejected: no reward beyond the entry")
    return {"ok": ok, "entry": round(entry, decimals), "stop": stop, "risk": round(risk, decimals),
            "target_one": round(target_one, decimals), "target_two": target_two, "reward": round(reward, decimals),
            "ratio": ratio, "detail": detail, "stop_detail": stop_detail,
            "target_detail": f"next liquidity is the {target_kind} at {target_one:g} on the {target_timeframe}"}


# --------------------------------------------------------------------------- #
# indicator context (RSI / SMA20 / SMA50 / ATR)
# --------------------------------------------------------------------------- #
def indicator_reads(closed: dict[str, list[Candle]], views: dict[str, TimeframeSMC]) -> tuple[IndicatorRead, ...]:
    """RSI (Wilder), SMA20, SMA50 and ATR on every supplied timeframe."""
    out: list[IndicatorRead] = []
    for timeframe in TIMEFRAMES:
        candles = closed.get(timeframe) or []
        if len(candles) < 21:
            continue
        closes = [candle.close for candle in candles]
        rsi = rsi_wilder(closes)
        sma20 = mean(closes[-20:])
        sma50 = mean(closes[-50:]) if len(closes) >= 50 else mean(closes)
        view = views.get(timeframe)
        atr = view.atr if view is not None else 0.0
        alignment = "bullish" if sma20 > sma50 else "bearish" if sma20 < sma50 else "flat"
        band = "overbought" if rsi >= 70 else "oversold" if rsi <= 30 else "neutral"
        note = (f"{timeframe}: RSI {rsi:.1f} ({band}), SMA20 {sma20:,.2f} "
                f"{'>' if sma20 > sma50 else '<' if sma20 < sma50 else '='} SMA50 {sma50:,.2f} "
                f"({alignment} alignment), ATR {atr:,.2f}")
        out.append(IndicatorRead(timeframe, rsi, round(sma20, 8), round(sma50, 8), atr, alignment, note))
    return tuple(out)


# --------------------------------------------------------------------------- #
# the chain
# --------------------------------------------------------------------------- #
def decide(
    asset_key: str,
    asset_name_ar: str,
    asset_name_en: str,
    quote: str,
    decimals: int,
    candles_by_timeframe: dict[str, list[Candle]],
    source: str = "",
    min_risk_reward: float = MIN_RISK_REWARD,
    now: datetime | None = None,
) -> StrictDecision:
    """Run the seven gates in order and return the strict decision."""
    views: dict[str, TimeframeSMC] = {}
    closed: dict[str, list[Candle]] = {}
    live_note = ""
    for timeframe in TIMEFRAMES:
        candles = candles_by_timeframe.get(timeframe)
        if not candles:
            continue
        usable = drop_forming(candles, timeframe, now)
        if len(usable) < len(candles):
            live_note = f"the last {timeframe} bar ({stamp(candles[-1])}) was still forming and is excluded"
        if not usable:
            continue
        try:
            views[timeframe] = analyze_timeframe(usable, timeframe, decimals)
        except ValueError:
            continue
        closed[timeframe] = usable
    if TREND_TIMEFRAME not in views:
        raise ValueError(f"at least {TREND_TIMEFRAME} closed candles are required to judge the trend")

    highest = views[TREND_TIMEFRAME]
    setup = views.get(SETUP_TIMEFRAME)
    trigger = views.get(ENTRY_TIMEFRAME) or setup or highest
    # the reference price for an entry is the newest *closed* bar across the
    # supplied timeframes, i.e. the trigger's close, not the 4H close
    price = trigger.price
    steps: list[Step] = []
    flags: list[str] = []
    if live_note:
        flags.append("forming_bar_dropped")

    # ---- step 1: trend ---------------------------------------------------- #
    trend, trend_detail, trend_numbers = trend_from_swings(highest.swings)
    side = {"bullish": "long", "bearish": "short"}.get(trend, "none")
    steps.append(Step(1, "trend", "Trend (4H)", side != "none", f"4H structure: {trend_detail}", trend_numbers))

    # ---- step 2: liquidity ------------------------------------------------ #
    liquidity = liquidity_map(views, side, price)
    liquidity_ok = side != "none" and liquidity["target"] is not None
    if side == "none":
        liquidity_detail = liquidity["detail"] + " | no directional target while the 4H ladder is unclear"
    elif liquidity["target"] is None:
        liquidity_detail = liquidity["detail"] + " | no resting liquidity in the direction of the trade"
    else:
        liquidity_detail = (f"{liquidity['detail']} | target {liquidity['target'].price:g} "
                            f"({liquidity['target'].kind}, {liquidity['target'].distance_pct}% away)")
    steps.append(Step(2, "liquidity", "Liquidity map", liquidity_ok, liquidity_detail,
                      {"target": liquidity["target"].price if liquidity["target"] else 0.0,
                       "position_pct": liquidity["position_pct"], "zone": liquidity["zone"],
                       "sweeps": list(liquidity["sweeps"])}))

    # ---- step 3: volume --------------------------------------------------- #
    confirmation = confirmation_analysis(views, side)
    volume = volume_filter(views, closed, side, confirmation)
    volume_ok = side != "none" and volume["passed"]
    steps.append(Step(3, "volume", "Volume filter", volume_ok, volume["detail"],
                      {"rvol": volume["rvol"], "rvol_setup": volume["setup_rvol"], "status": volume["status"],
                       "obv_slope": volume["obv_slope"], "buy_pct": volume["buy_pct"],
                       "problems": list(volume["problems"])}))
    if not volume_ok and side != "none":
        flags.append("volume_reject")

    # ---- step 4: structure confirmation ----------------------------------- #
    event = confirmation.get("event")
    structure_ok = side != "none" and bool(confirmation["ok"])
    steps.append(Step(4, "confirmation", "Structure confirmation (BOS/CHoCH)", structure_ok,
                      confirmation["detail"] or "no confirmation",
                      {"timeframe": confirmation.get("timeframe", ""),
                       "kind": event.label if event else "none",
                       "level": event.level if event else 0.0,
                       "time": event.time if event else "",
                       "volume_ratio": event.volume_ratio if event else 0.0}))

    # ---- step 5: candle confirmation -------------------------------------- #
    candle_view = views.get(confirmation.get("timeframe") or ENTRY_TIMEFRAME) or trigger
    candle = candle_confirmation(candle_view, side)
    candle_ok = side != "none" and candle["passed"]
    steps.append(Step(5, "candle", "Candle confirmation", candle_ok, candle["detail"],
                      {"signal": candle["signal"], "direction": candle["direction"],
                       "time": candle.get("time", ""), "timeframe": candle_view.timeframe}))

    # ---- step 6: entry zone ----------------------------------------------- #
    entry = entry_zone(views, closed, side, price, decimals, event.time if event else "",
                       confirmation.get("timeframe", ""))
    entry_ok = side != "none" and entry["ok"]
    steps.append(Step(6, "entry_zone", "Entry zone (OB/FVG return)", entry_ok, entry["detail"],
                      {"kind": entry["zone"].kind if entry.get("zone") else "none",
                       "bottom": entry["zone"].bottom if entry.get("zone") else 0.0,
                       "top": entry["zone"].top if entry.get("zone") else 0.0,
                       "tolerance": round(entry.get("tolerance", 0.0), 8)}))

    # ---- step 7: risk ----------------------------------------------------- #
    plan: dict = {"ok": False, "detail": "no valid entry zone, so there is no plan to size"}
    if entry_ok:
        plan = risk_plan(views, side, entry["zone"], price, decimals, min_risk_reward)
    steps.append(Step(7, "risk", "Risk management (reward:risk >= 2)", bool(plan.get("ok")), plan.get("detail", ""),
                      {key: plan[key] for key in ("entry", "stop", "target_one", "target_two", "risk", "reward", "ratio")
                       if key in plan}))

    # ---- final ------------------------------------------------------------ #
    # the chain stops at the first failure: later gates are no longer a reason
    # for the verdict, they were simply never reached
    first_failure = next((step for step in steps if not step.passed), None)
    stopped_at = first_failure.number if first_failure else 0
    if first_failure is not None:
        steps = [step if step.number <= stopped_at else replace(step, reached=False) for step in steps]
    all_passed = first_failure is None
    decision = ("buy" if side == "long" else "sell") if all_passed else "wait"
    confidence = "low"
    if all_passed:
        confluence = 0
        confluence += 1 if confirmation.get("sweeps") else 0
        confluence += 1 if volume["rvol"] >= 1.5 else 0
        confluence += 1 if (entry.get("zone") is not None and entry["zone"].fresh) else 0
        confluence += 1 if len(confirmation.get("aligned") or []) >= 2 else 0
        confluence += 1 if ((liquidity["zone"] == "discount" and side == "long")
                            or (liquidity["zone"] == "premium" and side == "short")) else 0
        confidence = "high" if confluence >= 3 else "medium"
    reasons = tuple(f"Step {step.number} ({step.title}): {step.detail}"
                    for step in steps if step.reached and not step.passed)
    if not all_passed and not reasons:  # pragma: no cover - defensive
        reasons = ("no gate returned a usable reading",)
    if stopped_at and stopped_at < 7:
        # the risk gate never ran, so there is no plan to quote: printing a stop
        # and a target here would look like a recommendation
        plan = {"ok": False, "detail": plan.get("detail", ""), "stop_detail": "", "target_detail": ""}

    target = liquidity["target"]
    return StrictDecision(
        asset_key=asset_key, asset_name_en=asset_name_en, asset_name_ar=asset_name_ar, quote=quote,
        decimals=decimals, price=round(price, decimals), source=source, as_of=trigger.as_of,
        timeframe_of_price=trigger.timeframe,
        trend=trend, trend_detail=trend_detail,
        liquidity_target=liquidity["direction"], liquidity_detail=liquidity_detail,
        liquidity_above=liquidity["above"], liquidity_below=liquidity["below"],
        premium_discount=liquidity["zone"], position_pct=liquidity["position_pct"],
        equal_highs=liquidity["equal_highs"], equal_lows=liquidity["equal_lows"], sweeps=liquidity["sweeps"],
        rvol=volume["rvol"], rvol_timeframe=volume["timeframe"], rvol_setup=volume["setup_rvol"],
        volume_status=volume["status"], volume_detail=volume["detail"], obv_slope=volume["obv_slope"],
        buy_pct=volume["buy_pct"],
        structure_confirmed=bool(confirmation["ok"]), structure_detail=confirmation["detail"],
        structure_event=event.label if event else "none", structure_timeframe=confirmation.get("timeframe", ""),
        structure_time=event.time if event else "", structure_level=event.level if event else 0.0,
        candle_signal=candle["signal"], candle_direction=candle["direction"], candle_timeframe=candle_view.timeframe,
        candle_time=candle.get("time", ""), candle_detail=candle["detail"],
        entry_low=entry["zone"].bottom if entry.get("zone") else 0.0,
        entry_high=entry["zone"].top if entry.get("zone") else 0.0,
        entry_kind=entry["zone"].kind if entry.get("zone") else "none",
        entry_detail=entry["detail"],
        stop=plan.get("stop", 0.0), stop_timeframe=(setup or highest).timeframe,
        stop_detail=plan.get("stop_detail", plan.get("detail", "")),
        take_profit=plan.get("target_one", 0.0), take_profit_two=plan.get("target_two", 0.0),
        target_detail=plan.get("target_detail", plan.get("detail", "")),
        risk=plan.get("risk", 0.0), reward=plan.get("reward", 0.0), risk_reward=plan.get("ratio", 0.0),
        indicators=indicator_reads(closed, views), steps=tuple(steps), decision=decision, side=side, confidence=confidence, reasons=reasons,
        flags=tuple(flags),
        views=tuple(views[timeframe] for timeframe in TIMEFRAMES if timeframe in views),
    )


# --------------------------------------------------------------------------- #
# rendering — the strict output format
# --------------------------------------------------------------------------- #
def _fmt(value: float, decimals: int) -> str:
    if not value:
        return "n/a"
    return f"{value:,.{decimals}f}"


def render(decision: StrictDecision, lang: str = "en", verbose: bool = False) -> str:
    """Render the strict block. ``lang`` is ``en``, ``ar`` or ``both``."""
    text = _render_ar(decision, verbose) if lang == "ar" else _render_en(decision, verbose)
    if lang == "both":
        return _render_en(decision, verbose) + "\n\n" + "—" * 18 + "\n\n" + _render_ar(decision, verbose)
    return text


def _render_en(decision: StrictDecision, verbose: bool) -> str:
    decimals = decision.decimals
    lines = [
        f"🧠 Smart Analysis | {decision.asset_key}",
        "",
        f"Trend (4H): {decision.trend.capitalize()}",
        f"Liquidity Target: {decision.liquidity_target.capitalize()}",
        "",
        "Volume:",
        f"- RVOL: {decision.rvol:.2f}x ({decision.rvol_timeframe})",
        f"- Status: {decision.volume_status.capitalize()}",
        "",
        "Structure:",
        f"- BOS / CHoCH: {'Yes' if decision.structure_confirmed else 'No'}",
        "",
        "Candles:",
        f"- Signal: {decision.candle_signal}",
        "",
        "Entry Zone:",
        f"- {_fmt(decision.entry_low, decimals)} - {_fmt(decision.entry_high, decimals)} ({decision.entry_kind})",
        "",
        "Stop Loss:",
        f"- {_fmt(decision.stop, decimals)}",
        "",
        "Take Profit:",
        *([f"- {_fmt(decision.take_profit, decimals)}",
           f"- {_fmt(decision.take_profit_two, decimals)} (second liquidity level)"]
          if decision.take_profit_two
          else [f"- {_fmt(decision.take_profit, decimals)}"]),
        "",
        "Risk/Reward:",
        f"- {decision.risk_reward:.2f} : 1",
        "",
        f"🎯 FINAL DECISION: {decision.decision_label}",
        f"Confidence: {decision.confidence.capitalize()}",
    ]
    if decision.decision == "wait":
        lines.append("")
        lines.append("⚠️ WAIT — exact reason:")
        lines.extend(f"- {reason}" for reason in decision.reasons)
    if verbose:
        lines.append("")
        lines.append("Gate chain (evaluated in this order, the first failure stops the chain):")
        for step in decision.steps:
            # reachability comes first: a gate that happens to be satisfied on
            # the raw data was still never reached once the chain had stopped
            marker = "not reached" if not step.reached else ("PASS" if step.passed else "FAIL")
            lines.append(f"[{marker}] {step.number}. {step.title}: {step.detail}")
        if 0 < decision.stopped_at < 7:
            lines.append(f"chain stopped at step {decision.stopped_at}; gates "
                         f"{decision.stopped_at + 1}-7 were not reached")
        if decision.indicators:
            lines.append("")
            lines.append("Indicator context (RSI / SMA20 / SMA50 / ATR — describes the backdrop, never a gate):")
            lines.extend(f"- {item.note}" for item in decision.indicators)
        lines.append("")
        lines.append(f"Reference price {_fmt(decision.price, decimals)} on {decision.timeframe_of_price} "
                     f"(forming bar excluded) | source {decision.source} | as of {decision.as_of}")
    return "\n".join(lines)


def _render_ar(decision: StrictDecision, verbose: bool) -> str:
    decimals = decision.decimals
    trend = {"bullish": "صاعد", "bearish": "هابط", "none": "غير واضح"}[decision.trend]
    target = {"up": "أعلى", "down": "أسفل", "both": "الاثنان"}[decision.liquidity_target]
    status = "قوي" if decision.volume_status == "strong" else "ضعيف"
    headline = {"buy": "شراء", "sell": "بيع", "wait": "انتظار"}[decision.decision]
    confidence = {"high": "عالية", "medium": "متوسطة", "low": "منخفضة"}[decision.confidence]
    lines = [
        f"🧠 تحليل ذكي | {decision.asset_key}",
        "",
        f"الاتجاه (4H): {trend}",
        f"هدف السيولة: {target}",
        "",
        "الحجم:",
        f"- RVOL: {decision.rvol:.2f}x ({decision.rvol_timeframe})",
        f"- الحالة: {status}",
        "",
        "الهيكل:",
        f"- BOS / CHoCH: {'نعم' if decision.structure_confirmed else 'لا'}",
        "",
        "الشموع:",
        f"- الإشارة: {decision.candle_signal}",
        "",
        "منطقة الدخول:",
        f"- {_fmt(decision.entry_low, decimals)} - {_fmt(decision.entry_high, decimals)} ({decision.entry_kind})",
        "",
        "وقف الخسارة:",
        f"- {_fmt(decision.stop, decimals)}",
        "",
        "الأهداف:",
        *([f"- {_fmt(decision.take_profit, decimals)}",
           f"- {_fmt(decision.take_profit_two, decimals)} (مستوى السيولة الثاني)"]
          if decision.take_profit_two
          else [f"- {_fmt(decision.take_profit, decimals)}"]),
        "",
        "العائد/المخاطرة:",
        f"- {decision.risk_reward:.2f} : 1",
        "",
        f"🎯 القرار النهائي: {headline}",
        f"الثقة: {confidence}",
    ]
    if decision.decision == "wait":
        lines.append("")
        lines.append("⚠️ انتظار — السبب المحدد:")
        lines.extend(f"- {reason}" for reason in decision.reasons)
    if verbose:
        lines.append("")
        lines.append("سلسلة البوابات (بهذا الترتيب، وأول فشل يوقف السلسلة):")
        for step in decision.steps:
            marker = "لم تُختبر" if not step.reached else ("نجحت" if step.passed else "فشلت")
            lines.append(f"[{marker}] {step.number}. {step.title}: {step.detail}")
        if 0 < decision.stopped_at < 7:
            lines.append(f"توقفت السلسلة عند البوابة {decision.stopped_at}؛ البوابات "
                         f"{decision.stopped_at + 1}-7 لم تُختبر")
        if decision.indicators:
            lines.append("")
            lines.append("قراءة المؤشرات (RSI / SMA20 / SMA50 / ATR — وصف للخلفية ولا تفتح صفقة بحد ذاتها):")
            lines.extend(f"- {item.note}" for item in decision.indicators)
        lines.append("")
        lines.append(f"السعر المرجعي {_fmt(decision.price, decimals)} على {decision.timeframe_of_price} "
                     f"(الشمعة الجارية مستبعدة) | المصدر {decision.source} | حتى {decision.as_of}")
    return "\n".join(lines)


def render_brief(decision: StrictDecision, lang: str = "en") -> str:
    prefix = "🧠 قرار" if lang == "ar" else "🧠 Verdict"
    extra = ""
    if decision.decision == "wait" and decision.reasons:
        extra = " | " + decision.reasons[0][:120]
    return (f"{prefix} {decision.asset_key}: {decision.decision_label} | {decision.trend} 4H | "
            f"RVOL {decision.rvol:.2f}x | RR {decision.risk_reward:.2f} | {decision.structure_event}{extra}")


def to_dict(decision: StrictDecision) -> dict:
    return {
        "asset": decision.asset_key,
        "name_en": decision.asset_name_en,
        "name_ar": decision.asset_name_ar,
        "price": decision.price,
        "price_timeframe": decision.timeframe_of_price,
        "source": decision.source,
        "as_of": decision.as_of,
        "trend_4h": decision.trend,
        "trend_detail": decision.trend_detail,
        "liquidity_target": decision.liquidity_target,
        "liquidity_detail": decision.liquidity_detail,
        "liquidity_above": decision.liquidity_above.__dict__ if decision.liquidity_above else None,
        "liquidity_below": decision.liquidity_below.__dict__ if decision.liquidity_below else None,
        "equal_highs": list(decision.equal_highs),
        "equal_lows": list(decision.equal_lows),
        "sweeps": list(decision.sweeps),
        "premium_discount": decision.premium_discount,
        "position_pct": decision.position_pct,
        "rvol": decision.rvol,
        "rvol_timeframe": decision.rvol_timeframe,
        "rvol_setup": decision.rvol_setup,
        "volume_status": decision.volume_status,
        "volume_detail": decision.volume_detail,
        "obv_slope": decision.obv_slope,
        "buy_pct": decision.buy_pct,
        "structure_confirmed": decision.structure_confirmed,
        "structure_event": decision.structure_event,
        "structure_timeframe": decision.structure_timeframe,
        "structure_time": decision.structure_time,
        "structure_level": decision.structure_level,
        "candle_signal": decision.candle_signal,
        "candle_timeframe": decision.candle_timeframe,
        "candle_time": decision.candle_time,
        "entry_low": decision.entry_low,
        "entry_high": decision.entry_high,
        "entry_kind": decision.entry_kind,
        "stop": decision.stop,
        "take_profit": decision.take_profit,
        "take_profit_two": decision.take_profit_two,
        "risk": decision.risk,
        "reward": decision.reward,
        "risk_reward": decision.risk_reward,
        "decision": decision.decision,
        "side": decision.side,
        "confidence": decision.confidence,
        "reasons": list(decision.reasons),
        "flags": list(decision.flags),
        "indicators": [
            {"timeframe": item.timeframe, "rsi": item.rsi, "sma20": item.sma20, "sma50": item.sma50,
             "atr": item.atr, "alignment": item.alignment, "note": item.note}
            for item in decision.indicators
        ],
        "steps": [
            {"number": step.number, "key": step.key, "title": step.title, "passed": step.passed,
             "reached": step.reached, "state": step.state, "detail": step.detail, "numbers": step.numbers}
            for step in decision.steps
        ],
    }
